### ISSUE TITLE
errors about funtion cam_to_label

### ISSUE THREAD

**Issue by process852** [zhenghuizhao/TransWCD#1]
Thank you very much for your excellent work!!!

One problem was found during code execution。

cam_to_label function only has four parameters, but in train_transwcd.py convert five parameters to this function.

![image](https://github.com/zhenghuizhao/TransWCD/assets/62278179/74f8476e-2123-4d23-acb8-094fc5a8f46e)

**Comment by zhenghuizhao** [comment]
Thank you for your reminder! This bug was fixed.

**Comment by process852** [comment]
Hi, I see you the modifications about the source code. You only add `cls_label` parameter, but this parameter was not used in this function.
![image](https://github.com/zhenghuizhao/TransWCD/assets/62278179/b53015f3-429a-4b80-b2a2-1fbc8c283205)

![image](https://github.com/zhenghuizhao/TransWCD/assets/62278179/83b80ff0-f20c-4866-9128-3fe0715146db)

**Comment by zhenghuizhao** [comment]
Thanks！The cls_label will be used for TransWCD-DL, so we keep it.
