### ISSUE TITLE
Questions about code integrity.

### ISSUE THREAD

**Issue by fL0n9** [zhenghuizhao/TransWCD#2]
Dear author, I have carefully read your public code, but the training script does not seem to involve the Dilated Prior Decoder and Labeled Gated Constraint mentioned in the paper. In addition, the code uses the pre-trained model parameters of SegFormer and relies on additional information, which seems to be contrary to the paradigm and principles of weakly supervised learning. I hope the author can answer these two questions in his busy schedule.

**Comment by zhenghuizhao** [comment]
Thank you for your attention! Our paper has not been accepted yet. We will update the code once it is accepted. Please stay tuned for further updates. For the pre-trained usage, we follow the previous weakly-supervised learning methods.  If you have any further questions, feel free to add me on WeChat: 904150289.
